Dealership.App/Dealership.App/Controllers/CarBrandController.cs
using AutoMapper;
using Dealership.App.FluentValidation;
using Dealership.App.Mediator.Commands;
using Dealership.App.Mediator.Queries;
using Dealership.App.Models.CarBrand;
using Dealership.Domain.Entities;
using Dealership.Domain.Interfaces;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Dealership.App.Controllers
{
    public class CarBrandController : Controller
    {
        private readonly IMediator _mediator;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public CarBrandController(IMediator mediator, IUnitOfWork unitOfWork, IMapper mapper)
        {
            this._mediator = mediator;
            this._unitOfWork = unitOfWork;
            this._mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<CarBrandViewModel> carBrands = await this._mediator.Send(new GetCarBrandsQuery());

            return View(carBrands);
        }

        public IActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(CreateCarBrandViewModel newBrand) 
        {
            if(ModelState.IsValid)
            {
                var response = await _mediator.Send(new CreateCarBrandCommand(newBrand));
                if (response)
                {
                    this._unitOfWork.Commit();
                }

                return RedirectToAction("Index");
            }

            return View("Create");
        }

        public async Task<IActionResult> Update(int? Id)
        {
            CarBrand brand = await this._mediator.Send(new GetCarBrandQuery(Id));
            UpdateCarBrandViewModel brandToView = this._mapper.Map<UpdateCarBrandViewModel>(brand);

            return View(brandToView);
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePost(UpdateCarBrandViewModel updatedBrand) 
        {
            var response = await this._mediator.Send(new UpdateCarBrandCommand(updatedBrand));

            if (ModelState.IsValid) 
            {
                if (response)
                {
                    this._unitOfWork.Commit();
                    return RedirectToAction("Index");
                }
            }

            return View("Update");
        }

        public async Task<IActionResult> Delete(int Id) 
        {
            CarBrand brand = await this._mediator.Send(new GetCarBrandQuery(Id));
            CarBrandViewModel brandToDelete = this._mapper.Map<CarBrandViewModel>(brand);

            return View(brandToDelete);
        }

        [HttpPost]
        public async Task<IActionResult> DeletePost(int CarBrandId) 
        {
            var deleteResponse = await this._mediator.Send(new DeleteCarBrandCommand(CarBrandId));

            if (deleteResponse) 
            {
                this._unitOfWork.Commit();
            }

            return RedirectToAction("Index");
        }
    }
}

Dealership.App/Dealership.App/Controllers/CarController.cs
using AutoMapper;
using Dealership.App.Mediator.Commands;
using Dealership.App.Mediator.Queries;
using Dealership.App.Models.Car;
using Dealership.Domain.Interfaces;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Dealership.App.Controllers
{
    public class CarController : Controller
    {
        private readonly IMediator _mediator;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;


        public CarController(IMediator mediator, IUnitOfWork unitOfWork, IMapper mapper)
        {
            this._mediator = mediator;
            this._unitOfWork = unitOfWork;
            this._mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<CarViewModel> carsToView = await this._mediator.Send(new GetCarsQuery());

            return View(carsToView);
        }

        public async Task<IActionResult> Create() 
        {
            CreateCarViewModel carModelToCreate = new()
            {
                CarBrands = await this._mediator.Send(new GetCarBrandsQuery()),
                CarModels = await this._mediator.Send(new GetCarModelsQuery())
            };
            return View(carModelToCreate);
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(CreateCarViewModel newCar) 
        {
            if (ModelState.IsValid) 
            {
                var createResponse = await this._mediator.Send(new CreateCarCommand(newCar));
                if (createResponse)
                {
                    this._unitOfWork.Commit();
                }

                return RedirectToAction("Index");
            }

            return View("Create");
        }

        public async Task<IActionResult> Update(int Id) 
        {
            var carToView = await this._mediator.Send(new GetCarQuery(Id));
            UpdateCarViewModel updateCarModel = this._mapper.Map<UpdateCarViewModel>(carToView);
            updateCarModel.CarBrands = await this._mediator.Send(new GetCarBrandsQuery());
            updateCarModel.CarModels = await this._mediator.Send(new GetCarModelsQuery());

            return View(updateCarModel);
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePost(UpdateCarViewModel updatedCar) 
        {
            var updateResponse = await this._mediator.Send(new UpdateCarCommand(updatedCar));

            if (ModelState.IsValid) 
            {
                if (updateResponse)
                {
                    this._unitOfWork.Commit();
                }

                return RedirectToAction("Index");
            }

            return View("Update");
        }

        public async Task<IActionResult> Delete(int Id) 
        {
            var car = await this._mediator.Send(new GetCarQuery(Id));
            CarViewModel carToDelete = this._mapper.Map<CarViewModel>(car);
            if (carToDelete == null) 
            {
                return RedirectToAction("Index");
            }

            return View(carToDelete);
        }

        [HttpPost]
        public async Task<IActionResult> DeletePost(CarViewModel carToDelete)
        {
            var deleteResponse = await this._mediator.Send(new DeleteCarCommand(carToDelete));

            if (deleteResponse) 
            {
                this._unitOfWork.Commit();
            }

            return RedirectToAction("Index");
        }
    }
}

Dealership.App/Dealership.App/Controllers/CarModelController.cs
using AutoMapper;
using Dealership.App.Mediator.Commands;
using Dealership.App.Mediator.Queries;
using Dealership.App.Models.CarModel;
using Dealership.Domain.Entities;
using Dealership.Domain.Interfaces;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Dealership.App.Controllers
{
    public class CarModelController : Controller
    {
        private readonly IMediator _mediator;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public CarModelController(IMediator mediator, IUnitOfWork unitOfWork, IMapper mapper)
        {
            this._mediator = mediator;
            this._unitOfWork = unitOfWork;
            this._mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<CarModelViewModel> models = await this._mediator.Send(new GetCarModelsQuery());

            return View(models);
        }

        public IActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(CreateCarModelViewModel newCarModel) 
        {
            var response = await this._mediator.Send(new CreateCarModelCommand(newCarModel));

            if (ModelState.IsValid) 
            {
                if (response)
                {
                    this._unitOfWork.Commit();
                    return RedirectToAction("Index");
                }
            }

            return View("Create");
        }

        public async Task<IActionResult> Update(int Id) 
        {
            CarModel carModel = await this._mediator.Send(new GetCarModelQuery(Id));
            if (carModel == null) 
            {
                return RedirectToAction("Index");
            }
            UpdateCarModelViewModel carModelToUpdate = this._mapper.Map<UpdateCarModelViewModel>(carModel);

            return View(carModelToUpdate);
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePost(UpdateCarModelViewModel updatedCarModel)
        {
            var response = await this._mediator.Send(new UpdateCarModelCommand(updatedCarModel));

            if (ModelState.IsValid) 
            {
                if (response)
                {
                    this._unitOfWork.Commit();
                    return RedirectToAction("Index");
                }
            }

            return View("Update");
        }

        public async Task<IActionResult> Delete(int Id)
        {
            CarModel carModel = await this._mediator.Send(new GetCarModelQuery(Id));
            if (carModel == null) 
            {
                return RedirectToAction("Index");
            }
            CarModelViewModel carModelToDelete = this._mapper.Map<CarModelViewModel>(carModel);

            return View(carModelToDelete);
        }

        [HttpPost]
        public async Task<IActionResult> DeletePost(int CarModelId) 
        {
            var response = await this._mediator.Send(new DeleteCarModelCommand(CarModelId));
            this._unitOfWork.Commit();

            return RedirectToAction("Index");
        }
    }
}

Dealership.App/Dealership.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"] - Dealership.App</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <style>
        html, body, h1, h2, h3, h4, h5 {
            font-family: "Raleway", sans-serif
        }
    </style>
</head>
<body class="w3-light-grey">

    <!-- Top container -->
    <div class="w3-bar w3-top w3-black w3-large" style="z-index:4">
        <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i> &nbsp;Menu</button>
        <span class="w3-bar-item w3-right">Logo</span>
    </div>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar">
    <br>
    <div class="w3-container w3-row">
        <div class="w3-col s4">
            <img src="/w3images/avatar2.png" class="w3-circle w3-margin-right" style="width:46px">
        </div>
        <div class="w3-col s8 w3-bar">
            <span>Welcome, <strong>Mike</strong></span><br>
            <a href="#" class="w3-bar-item w3-button"><i class="fa fa-envelope"></i></a>
            <a href="#" class="w3-bar-item w3-button"><i class="fa fa-user"></i></a>
            <a href="#" class="w3-bar-item w3-button"><i class="fa fa-cog"></i></a>
        </div>
    </div>
    <hr>
    <div class="w3-container">
        <h5>Dashboard</h5>
    </div>
    <div class="w3-bar-block">
        <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>&nbsp; Close Menu</a>
        <a asp-action="Index" asp-controller="Home" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>&nbsp; Home</a>
        <a asp-action="Index" asp-controller="Car" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>&nbsp; Available Stock</a>
        <a asp-action="Create" asp-controller="Car" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>&nbsp; Add Stock</a>
        <a asp-action="Index" asp-controller="CarBrand" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>&nbsp; All Brands</a>
        <a asp-action="Create" asp-controller="CarBrand" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>&nbsp; Create New Brand</a>
        <a asp-action="Index" asp-controller="CarModel" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>&nbsp; All Models</a>
        <a asp-action="Create" asp-controller="CarModel" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>&nbsp; Creat New Car Model</a>
    </div>
</nav>


<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px;margin-top:43px;">
<!-- Header -->
<header class="w3-container" style="padding-top:22px">
    <h5><b><i class="fa fa-dashboard"></i> My Dashboard</b></h5>
</header>
    @RenderBody()
    <footer class="w3-container w3-padding-16 w3-light-grey">
        <h4>FOOTER</h4>
        <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
    </footer>
    <!-- End page content -->
</div>

    <script>
        // Get the Sidebar
        var mySidebar = document.getElementById("mySidebar");

        // Get the DIV with overlay effect
        var overlayBg = document.getElementById("myOverlay");

        // Toggle between showing and hiding the sidebar, and add overlay effect
        function w3_open() {
            if (mySidebar.style.display === 'block') {
                mySidebar.style.display = 'none';
                overlayBg.style.display = "none";
            } else {
                mySidebar.style.display = 'block';
                overlayBg.style.display = "block";
            }
        }

        // Close the sidebar with the close button
        function w3_close() {
            mySidebar.style.display = "none";
            overlayBg.style.display = "none";
        }
    </script>
</body>
</html>